version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./services/db/data:/var/lib/postgresql/data/
    #env_file:
    #  - ./services/db/.postgres.env
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vekings 
    ports:
      - 8001:5432 

  server:
    build: ./services/server
    ports:
      - 8000:8000
    depends_on:
      - db
    #volumes:
    #  - ./services/server/app:/app/app

